const SUPABASE_URL     = 'https://qobsznttpnrlzqjodyym.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvYnN6bnR0cG5ybHpxam9keXltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODEzOTIzMTUsImV4cCI6MjA5Njk2ODMxNX0.IJrBlo7CL3xjbFBfSSTOov_FKflzsazewDrjp7EVIrs';
